# Generated by Django after Pessoa became a User subclass.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plantas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=models.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14, unique=True, verbose_name="CPF"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="data de nascimento",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "Feminino"),
                            ("M", "Masculino"),
                            ("O", "Outro"),
                            ("N", "Prefiro não informar"),
                        ],
                        max_length=1,
                        verbose_name="sexo",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="número"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="bairro"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="cidade"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="estado"
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="CEP"
                    ),
                ),
                (
                    "plantas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pessoas",
                        to="plantas.planta",
                    ),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
                "ordering": ("first_name", "username"),
            },
            bases=("auth.user",),
        ),
    ]
