# Generated by Django after switching to the built-in User model.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plantas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14, unique=True, verbose_name="CPF"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="data de nascimento",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "Feminino"),
                            ("M", "Masculino"),
                            ("O", "Outro"),
                            ("N", "Prefiro não informar"),
                        ],
                        max_length=1,
                        verbose_name="sexo",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="número"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="bairro"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="cidade"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="estado"
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="CEP"
                    ),
                ),
                (
                    "plantas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pessoas",
                        to="plantas.planta",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pessoa",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
                "ordering": (
                    "usuario__first_name",
                    "usuario__username",
                ),
            },
        ),
    ]
