# Generated by Django 6.0.7 on 2026-08-25 14:48

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pessoa',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
