# Generated by Django 6.0.3 on 2026-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('plantas', '0006_planta_categoria'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[migrations.AlterField(
            model_name='pessoa',
            name='plantas',
            field=models.ManyToManyField(blank=True, related_name='pessoas', to='plantas.planta'),
        )]),
    ]
