# Generated by Django 6.0.3 on 2026-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoa_plantas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ('nome',), 'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='', max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cep',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='CPF'),
        ),
    ]
