# Generated by Django 6.0.3 on 2026-08-25 16:06

import Pessoas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_pessoa_options_pessoa_email_pessoa_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[Pessoas.models.validar_cpf], verbose_name='CPF'),
        ),
    ]
