# Generated by Django 6.1 on 2026-09-15 17:20

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


def ajustar_relacao_com_plantas(apps, schema_editor):
    pessoa = apps.get_model("pessoas", "Pessoa")
    through = pessoa.plantas.through
    quote = schema_editor.connection.ops.quote_name

    schema_editor.execute(
        f"UPDATE {quote('auth_user')} "
        f"SET email = (SELECT email FROM {quote(pessoa._meta.db_table)} "
        f"pessoa WHERE pessoa.usuario_id = {quote('auth_user')}.id) "
        f"WHERE id IN (SELECT usuario_id FROM {quote(pessoa._meta.db_table)})"
    )
    schema_editor.execute(
        f"UPDATE {quote(through._meta.db_table)} "
        f"SET pessoa_id = (SELECT usuario_id "
        f"FROM {quote(pessoa._meta.db_table)} pessoa "
        f"WHERE pessoa.id = {quote(through._meta.db_table)}.pessoa_id)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ajustar_relacao_com_plantas),
                migrations.RunSQL(
                    "ALTER TABLE pessoas_pessoa "
                    "RENAME COLUMN usuario_id TO user_ptr_id",
                    "ALTER TABLE pessoas_pessoa "
                    "RENAME COLUMN user_ptr_id TO usuario_id",
                ),
                migrations.RemoveField(
                    model_name="pessoa",
                    name="email",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="pessoa",
                    name="id",
                ),
                migrations.RemoveField(
                    model_name="pessoa",
                    name="usuario",
                ),
                migrations.RemoveField(
                    model_name="pessoa",
                    name="email",
                ),
                migrations.AddField(
                    model_name="pessoa",
                    name="user_ptr",
                    field=models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
