# Generated by Django 6.1 on 2026-09-15 17:31

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_herdar_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pessoa',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
