# Generated by Django 6.1 on 2026-09-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_alter_pessoa_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='sexo',
        ),
    ]
