# Generated by Django 6.0.3 on 2026-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantas', '0005_remove_planta_categoria_remove_cuidados_planta_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'plantas_categoria',
                'ordering': ('nome',),
            },
        )]),
    ]
