# Generated by Django 6.0.3 on 2026-08-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantas', '0006_planta_categoria'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[migrations.CreateModel(
            name='Cuidados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.JSONField(default=list, verbose_name='tipos de cuidado')),
                ('data', models.DateField(verbose_name='data')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuidados', to='plantas.planta', verbose_name='planta')),
            ],
            options={
                'verbose_name': 'cuidado',
                'verbose_name_plural': 'cuidados',
                'db_table': 'plantas_cuidados',
                'ordering': ('-data',),
            },
        )]),
    ]
