# Generated by Django 6.0.3 on 2026-08-25 16:01

from django.db import migrations, models


def migrar_tipos_existentes(apps, schema_editor):
    Cuidados = apps.get_model("cuidados", "Cuidados")
    TipoDeCuidado = apps.get_model("cuidados", "TipoDeCuidado")
    tipo_ativo = TipoDeCuidado.objects.create(
        codigo="cuidado_ativo",
        nome="Cuidado ativo",
    )
    for cuidado in Cuidados.objects.filter(tipo=True):
        cuidado.tipos_novos.add(tipo_ativo)


def reverter_tipos_existentes(apps, schema_editor):
    Cuidados = apps.get_model("cuidados", "Cuidados")
    for cuidado in Cuidados.objects.all():
        cuidado.tipo = cuidado.tipos_novos.exists()
        cuidado.save(update_fields=["tipo"])


class Migration(migrations.Migration):

    dependencies = [
        ('cuidados', '0002_alter_cuidados_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'tipo de cuidado',
                'verbose_name_plural': 'tipos de cuidado',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='cuidados',
            name='tipos_novos',
            field=models.ManyToManyField(related_name='cuidados', to='cuidados.tipodecuidado', verbose_name='tipos de cuidado'),
        ),
        migrations.RunPython(
            migrar_tipos_existentes,
            reverter_tipos_existentes,
        ),
        migrations.RemoveField(
            model_name='cuidados',
            name='tipo',
        ),
        migrations.RenameField(
            model_name='cuidados',
            old_name='tipos_novos',
            new_name='tipo',
        ),
    ]
