# Generated by Django 6.1 on 2026-09-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuidados', '0004_popular_tipos_de_cuidado'),
        ('plantas', '0008_remove_planta_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuidado',
            new_name='Cuidados',
        ),
    ]
