# Generated by Django 5.2.13 on 2026-08-18 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=150, verbose_name='nome científico')),
                ('nome_popular', models.CharField(max_length=150, verbose_name='nome popular')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='data de cadastro')),
                ('data_plantio', models.DateField(blank=True, null=True, verbose_name='data de plantio')),
                ('status', models.CharField(default='ativa', max_length=20, verbose_name='status')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantas', to='plantas.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'planta',
                'verbose_name_plural': 'plantas',
                'ordering': ('nome_popular', 'nome_cientifico'),
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='plantas/fotografias/', verbose_name='imagem')),
                ('data_foto', models.DateField(verbose_name='data da foto')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='plantas.planta', verbose_name='planta')),
            ],
            options={
                'verbose_name': 'fotografia',
                'verbose_name_plural': 'fotografias',
                'ordering': ('-data_foto',),
            },
        ),
        migrations.CreateModel(
            name='Cuidados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.JSONField(default=list, verbose_name='tipos de cuidado')),
                ('data', models.DateField(verbose_name='data')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuidados', to='plantas.planta', verbose_name='planta')),
            ],
            options={
                'verbose_name': 'cuidado',
                'verbose_name_plural': 'cuidados',
                'ordering': ('-data',),
            },
        ),
    ]
