# Generated by Django 6.1 on 2026-08-24 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planta",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plantas",
                to="plantas.categoria",
                verbose_name="categoria",
            ),
        ),
    ]
