# Generated by Django 6.0.7 on 2026-08-25 14:55

from django.db import migrations, models


TIPOS_DE_CUIDADO = (
    ("regar_muito", "Regar muito"),
    ("regar_moderadamente", "Regar moderadamente"),
    ("regar_pouco", "Regar pouco"),
    ("fertilizar", "Adicionar fertilizante"),
    ("podar", "Podar regularmente"),
    ("luz_direta", "Manter sob luz direta"),
    ("luz_indireta", "Manter em lugar iluminado"),
    ("sombra", "Manter em local sombreado"),
    ("controlar_pragas", "Controlar pragas"),
    ("trocar_substrato", "Trocar o substrato"),
)


def migrar_tipos_existentes(apps, schema_editor):
    TipoDeCuidado = apps.get_model("plantas", "TipoDeCuidado")
    Cuidados = apps.get_model("plantas", "Cuidados")

    tipos = {
        codigo: TipoDeCuidado.objects.create(codigo=codigo, nome=nome)
        for codigo, nome in TIPOS_DE_CUIDADO
    }
    for cuidado in Cuidados.objects.all():
        cuidado.tipos_novos.set(
            [tipos[codigo] for codigo in cuidado.tipo if codigo in tipos]
        )


def remover_tipos_migrados(apps, schema_editor):
    Cuidados = apps.get_model("plantas", "Cuidados")
    for cuidado in Cuidados.objects.all():
        cuidado.tipo = list(
            cuidado.tipos_novos.values_list("codigo", flat=True)
        )
        cuidado.save(update_fields=["tipo"])


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_cuidados_multiplos_tipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'tipo de cuidado',
                'verbose_name_plural': 'tipos de cuidado',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='cuidados',
            name='tipos_novos',
            field=models.ManyToManyField(related_name='cuidados', to='plantas.tipodecuidado', verbose_name='tipos de cuidado'),
        ),
        migrations.RunPython(migrar_tipos_existentes, remover_tipos_migrados),
        migrations.RemoveField(
            model_name='cuidados',
            name='tipo',
        ),
        migrations.RenameField(
            model_name='cuidados',
            old_name='tipos_novos',
            new_name='tipo',
        ),
    ]
