# Generated by Django 6.0.3 on 2026-08-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('plantas', '0004_merge'),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=[
        migrations.RemoveField(
            model_name='planta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='cuidados',
            name='planta',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='planta',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cuidados',
        ),
        migrations.DeleteModel(
            name='Fotografia',
        ),
    ])]
