# Generated by Django 6.0.3 on 2026-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0006_planta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='status',
            field=models.CharField(default='ativa', max_length=20, verbose_name='status'),
        ),
    ]
