# Generated by Django 6.1 on 2026-08-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0007_planta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='status',
        ),
    ]
