# Generated by Django 6.0.3 on 2026-08-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantas', '0006_planta_categoria'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='plantas/fotografias/', verbose_name='imagem')),
                ('data_foto', models.DateField(verbose_name='data da foto')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='plantas.planta', verbose_name='planta')),
            ],
            options={
                'verbose_name': 'fotografia',
                'verbose_name_plural': 'fotografias',
                'db_table': 'plantas_fotografia',
                'ordering': ('-data_foto',),
            },
        )]),
    ]
